export { Home } from './home/Home'
export { Career } from './career/Career'
export { Portfolio } from './portfolio/Portfolio'
export { Skills } from './skills/Skills'
export { ToyProjects } from './toyProjects/ToyProjects'